### PR TITLE
Add datetime-local support

### PR DESCRIPTION
**Pull request by jrsquared**

### CODE REVIEW

**Comment by dannyshmueli** [comment]
+1 on merging this to master

**Comment by mitcht** [comment]
You don't need to commit the files from the dist directory. They get built automatically, and just clutters up the commit.  There may be additional files that do not need to be committed as well (possibly the zip files)

**Comment by jrsquared** [comment]
@mitcht Correct, but they are already in the repo, so it makes sense to at least keep them up to date until the repo owner decides to remove them and add then to .gitignore.

**Comment by mitcht** [comment]
@jrsquared dist files have to be in the repo because it is a bower package. Adding them to .gitignore would break the package installation process. We could probably argue on this, but the point I meant to make is that you might want to have the cleanest commit possible. Whoever it is out there that has to look at your request only will see the really important bits. It makes it more likely for them to just merge it.

**Comment by eugef** [comment]
Fixed by #473

**Pull request closed without merging**
