### PR TITLE
Fix for non-working form submit

### PR DESCRIPTION
**Pull request by lu4**
When xeditable is placed into custom directive like:

``` html
        <tabset>
            <tab ng-repeat="(documentTemplateVid, documentTemplateV) in documentTemplateR.versions track by documentTemplateVid">
                <tab-heading>
                    <a href="#" editable-text="documentTemplateV.title">{{ documentTemplateR.title || "Title absent" }}</a>
                </tab-heading>
                <div class="row">
                    <div class="col-xs-12">
                        <div summernote ng-model="documentTemplateV.content">
                        </div>
                        <div class="text-right">
                            <button type="button" class="btn btn-primary" ng-click="">Save</button>
                            <button type="button" class="btn btn-primary" ng-click="">Cancel</button>
                        </div>
                    </div>
                </div>
            </tab>
        </tabset>
```

xeditable stops working because `<button type="submit" >` wont fire submit event

### CODE REVIEW

**Comment by ckosloski** [comment]
This change breaks many tests because the tests specifically look for a submit button to click.  Fix the tests and don't submit the dist files with your request.

**Comment by ckosloski** [comment]
@lu4 can you update your request?

**Comment by lu4** [comment]
Not sure that I remember what it had to do with the project, afaik there's no reason to make the fix since angular-xeditable is targeted at Angular 1 rather than 2, no new projects start with Angular 1 so nobody will ever need the fix, sorry... (((

**Comment by ckosloski** [comment]
ok, do you want to close this request then?

**Comment by lu4** [comment]
Yeah, I'll do it

**Pull request closed without merging**
