### PR TITLE
Support for bootstrap-ui datepicker

### LINKED ISSUE #255: editable-bsdate not working in editable form (see jsfiddle)
I can't seem to get the editable-bsdate working within an editableform.

See jsfiddle below:

http://jsfiddle.net/yvanqt4a/

### PR DESCRIPTION
**Pull request by Painyjames**
Basically, I just render a datepicker with all the attributes set to default if not overriden. 
As in the example, a couple of attributes are needed (e-is-opened and e-ng-click).
I guess the example in the demo is good enough.
it fixes #255 and #248

Please let me know if something else is needed.

Cheers!

### CODE REVIEW

**Comment by nemes1s** [comment]
Hello, tried out this solution with 0.1.9 and bootstrap-tpls version 0.11.2.

Basically <span e-class="form-control" editable-bsdate="price.date" e-form="price_rowform" e-is-open="opened" e-ng-click="opened = !opened" e-datepicker-popup="yyyy-MM-dd">{{price.date || null}}</span>

Transforms into input with a calender button, but the datepicker is not shown on neither input click nor button click. Can you please provide a working example? Thank you!

**Comment by Painyjames** [comment]
Sure, I just need to update the angular-xeditable demo page with the example on it.
I'll try to do as soon as possible, hopefully before next week.

Cheers

**Comment by Painyjames** [comment]
Hi again,

I still couldn't release the new version on the demo web, but I did a jsfiddle if you can find it useful.
(Disregard the lack of icons, haven't loaded the fonts on this example)
http://jsfiddle.net/NfPcH/7249/

**Comment by nemes1s** [comment]
Thanks a lot! :+1:

**Comment by nemes1s** [comment]
Also, i've noticed that using editable-bsdate with editable-form doesn't update the field in $data.

Looking at the code, i've changed line 100 in xeditable.js: **ng-model="$data"** to **ng-model="$parent.$data"**

**Comment by HariBabuThubati** [comment]
@Painyjames  : Date picker is not working ..

<div ng-controller="BsdateCtrl">
  <a href="#" editable-bsdate="user.dob" e-datepicker-popup="dd-MMMM-yyyy">
    {{ (user.dob | date:"dd/MM/yyyy") || 'empty' }}
  </a>
</div>

var app = angular.module("myApp", ["xeditable", "ui.bootstrap"]);

app.run(function(editableOptions) {
  editableOptions.theme = 'bs3';
});

app.controller('BsdateCtrl', function($scope) {
	  $scope.user = {
	    dob: new Date(1984, 4, 15)
	  };
	});

**Pull request merged**
