### PR TITLE
editableConfig.editableTagsInput.inputTpl added

### PR DESCRIPTION
**Pull request by aecepoglu**
added `module.constant('editableConfig'`. Can use other libraries for ngTagsInput.

### CODE REVIEW

**Comment by aecepoglu** [comment]
With these changes other tags input libraries can be used with xeditable.

    myApp.config(function(editableConfig) {
        editableConfig.editableTagsInput.inputTpl = "<chips>...</chips>";
    })

And then use `editable-generic-tags-input` instead of `editable-tags-input`

    <div editable-generic-tags-input="myTags"></div>

That's all.

I believe this approach can also be used to make other views more extensible.

**Comment by eugef** [comment]
@aecepoglu please include only `src` folder in your PR

**Comment by ckosloski** [comment]
Hi @aecepoglu, thanks for the pull request.  A couple of things need to be changed.

- Remove all generated files from your request.
- Move your new directive to it's own file.
- Update the documentation.
- Add a test
- Do all of the existing tests pass?

**Comment by aecepoglu** [comment]
I assumed because they weren't .gitignore'd they were wanted.

Anyway, I'm going to need to extend the `mixin props(items` in *docs/jade/reference.json* because my items are objects and this mixin doesn't seem to handle them.

What would you like the output table to look like?

So this is what I'm trying to document:

    editableGenericTagsInput: { inputTpl: "..." }

And the mixin outputs table of this form:

    Name | Type | Description

So will this suffice?

    editableGenericTagsInput | Object | An object of the form `{inputTpl: "...", otherAttributesMaybe: "..."}`.
                                              |             | *inputTpl: the html template to use for the tags input directive

**Comment by ckosloski** [comment]
For documentation you could just add a new folder to the "docs" folder and model it after an existing documented item.
Put the documentation in the desc.md file, an example in the controller.js/view.html file and a test in test.js file.  Then update structure.js to add your documentation, maybe in the "Techniques" section.

**Comment by ckosloski** [comment]
@aecepoglu can you update your pull request?

**Comment by ckosloski** [comment]
@aecepoglu can you update your pull request?

**Comment by ckosloski** [comment]
@aecepoglu do you need any help getting this pr updated?

**Comment by aecepoglu** [comment]
Oh no no, I just can't find the time or motivation to do it; and I feel nobody is interested in the feature anyway. If you or someone else would like it added, I can make an effort. Otherwise we can close this.

**Comment by ckosloski** [comment]
Yeah, this has been here for a while and no one has commented that they wanted it.  I am fine with you closing it.

**Pull request closed without merging**
