### PR TITLE
allow users to disable checkboxes based on a condition

### LINKED ISSUE #744: Is there a way to disable a checkboxe inside a checklist?
I want to disable some checkboxes based on a condition, but i'm not finding a way to do it. Is there someone that can help me?

version: 0.8.1

code:
```html
<a 
           href="#" 
           onaftersave="updateUser()" 
           editable-checklist="obj.roles" 
           e-ng-options="s.value as s.text for s in userService.all_roles"
     > 
     <span ng-bind-html="showRoles()"></span>
  </a>
```

### PR DESCRIPTION
**Pull request by lohxx**
* allow users to disable checkboxes based on a condition.
* Update the docs
fixes #744

### CODE REVIEW

**Comment by ckosloski** [comment]
Can you squash your commits?

**Comment by ckosloski** [comment]
@eugef do you want to merge?

**Comment by lohxx** [comment]
Any updates?

**Comment by ckosloski** [comment]
I can't merge, only @eugef can.

**Comment by eugef** [comment]
@lohxx thanks for your PR

**Pull request merged**
