### PR TITLE
NuGet Packaging

### PR DESCRIPTION
**Pull request by markvp**
Hey Vitaliy, et al;

We are using angular-xeditable in a Visual Studio development environment and find it a lot easier to manage our dependencies using NuGet.

Is there any chance of you building nuget packages with your releases?

It's pretty simple, I've created a basic nuget.spec files and updated the Readme.MD to include some basic installation instructions.

Effort on your part:
1. Create a NuGet account
2. Review / update .nuspec files
3. Update build action for release build to update version in .nuspec file and publish to nuget,org

NuGet package publication info available at: http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package

Alternatively, we are happy to use our NuGet account to upload to nuget.org if you are in a linux environment and wish to avoid using mono (all we ask if that you leave the ADAPTByDesign references in the .nupsec file if we do - otherwise feel free to remove them!). If this is your preferred option, you will still need to update the version number in the .nuspec file when you build a release.

Thanks!

Mark

### CODE REVIEW

**Comment by MaitreDede** [comment]
Would be a lovely feature :)

**Comment by eugef** [comment]
@markvp does this feature still make sense?

**Comment by markvp** [comment]
@eugef, we're no longer using NuGet or xeditable so are unable to continue this contribution.

Sorry.

**Comment by eugef** [comment]
No problem.

**Pull request closed without merging**
