### PR TITLE
added fallback to focus on activate

### PR DESCRIPTION
**Pull request by Carnid**

### CODE REVIEW

**Comment by ckosloski** [comment]
Thanks for opening a new one.  Can you delete the other one?

**Comment by Carnid** [comment]
Done. Running a few final tests.

**Comment by eugef** [comment]
@Carnid could you describe the purpose of the PR?

**Comment by Carnid** [comment]
@eugef It solves this issue here: https://github.com/vitalets/angular-xeditable/issues/547

**Comment by Carnid** [comment]
Thought I had already mentioned it. I am satisfied with the tests.

**Comment by eugef** [comment]
@Carnid, thanks for your PR

**Pull request merged**
