### PR TITLE
Fixed #211:ui-select support

### LINKED ISSUE #211: Need xeditable in table with ui.select is put in a cell
When I worked with ng-repeat to render data in table tr . I need to edit in a cell with data is pulled from ui.select with multiple data in this select (picture, text) . I read from documents of xeditable currently only support typehead or select. It is not enough. when ui.select is appeared.

Many thanks if any guys can tell me way to reach that issue.

### PR DESCRIPTION
**Pull request by zhendong590**
i found a way to fox issue #211 ,merge these codes it can work fine.it also needs the 
[ui-select.js](http://github.com/angular-ui/ui-select "Title")

### CODE REVIEW

**Comment by JobaDiniz** [comment]
+1

**Comment by JobaDiniz** [comment]
@zhendong590, I think you modified the wrong file. You should create another *js* file in [this folder](https://github.com/vitalets/angular-xeditable/tree/master/src/js/directives). Grunt compilation will take care of adding the new file to the dist js...

**Comment by JobaDiniz** [comment]
@zhendong590 , it doesn't work for me... :cry: 
_model_ value (state.selected) is not updated:

```
<form name="addressForm" class="password-form col-md-8" ng-show="addressForm.$visible" onaftersave="updateAddress($data, addressForm)" editable-form novalidate>

<span editable-ui-select="state.selected" e-form="addressForm" e-name="state" name="state" theme="bootstrap" e-ng-model="state.selected">
                                    <editable-ui-select-match placeholder="State">{{$select.selected}}</editable-ui-select-match>
                                    <editable-ui-select-choices repeat="state in states | filter: $select.search">
                                        <span ng-bind-html="state | highlight: $select.search"></span>
                                    </editable-ui-select-choices>
                                </span>

</form>
```

**Comment by zhendong590** [comment]
@JobaDiniz could you make a jsfiddle for me ?

**Comment by eugef** [comment]
@zhendong590 , could you please provide code example how to use this new feature (preferably in plunker or jsfiddle)

**Comment by chepilot** [comment]
@zhendong590, could you make a example of using ui-select with angular-xeditable? Tried to use your code but can't make it work. Thanks.

**Comment by chepilot** [comment]
This fix seems not working with append-to-body of ui-select.

**Comment by polybioz** [comment]
@zhendong590 the fix does not work for me either, the model is not updated when the form is saved. See http://plnkr.co/edit/YTuBlsxEjCpXeILvpjry?p=preview

**Comment by cina2012** [comment]
i have same problem.
model value is not updated.
can you help me?
tnx.

**Comment by rafa-aguilar** [comment]
Same problem with model

**Comment by eugef** [comment]
Implemented by #451

**Pull request closed without merging**
