### PR TITLE
ng-model:

### PR DESCRIPTION
**Pull request by Mcafee123**
- allow to define my own model directly on editable span element

### CODE REVIEW

**Comment by Mcafee123** [comment]
this is my first pull request. please tell me if i have made anything wrong or informations are missing ;-)

explanation:
i have models that support validation and can apply or reject changes. i would like to be able to bind these directly to in place editable elements. i propose to change the code so that $data is only added as a model if there is not already another ng-model directive on the element.

**Comment by eugef** [comment]
@Mcafee123 , could you please add a simple code example how to use this new feature (preferably in Plunker or something similar)

**Comment by ckosloski** [comment]
@Mcafee123 is this pull request still relevant?

**Comment by Mcafee123** [comment]
@ckosloski: in one of my projects i use a version where i modified this. at the moment, i'm far away from this and cannot test anything, so feel free to delete the pull request.

**Pull request closed without merging**
