### PR TITLE
Watch for changes to edit-disabled

### PR DESCRIPTION
**Pull request by area**
I was happy to see that #235 had been merged into `dev`, as this was functionality I was looking to use. However, I was expecting the 'edit-ability' of the elements to follow the angular variable they were bound to, but because the directive was only applied upon the original load, any changes to that variable were not propagated.

I have added a watch to create (my) desired behaviour, and I wouldn't have thought I would be the only one expecting this variable to behave like this. I am reasonably new to angular though, so I'd be interested in knowing if there is an obvious reason I am not aware of that the original author of #235 (@hammat) didn't include this.

### CODE REVIEW

**Comment by area** [comment]
This PR should not be accepted in this state - it includes a dirty hack around a bug I have discovered in this implementation. I am hoping someone more versed in angular than I am can figure out the subtlety I am missing, which only appears to rear its head when `edit-disabled` is set to an angular variable on the input.

**Comment by area** [comment]
I note that #282 takes a different approach to solve the same problem, but it does not remove the styling associated with clickable elements, which my approach does - if the above bug can be fixed!

**Comment by ckosloski** [comment]
@area did you ever figure out a better approach?

**Comment by ckosloski** [comment]
@eugef Since the code doesn't work in the request, I propose it should be closed.

**Pull request closed without merging**
