### PR TITLE
Fix editable-combodate for single date fields

### LINKED ISSUE #705: editable-combodate multiple problems.
I am having some troubles with editable-combodate when used with different formats. 

Please refer to this [fiddle](https://jsfiddle.net/josemonsalve2/1yjatoxo).

First if you only have Year (YYYY) format, the displayed value gets reduced by one after submission, even though the angular model is updated correctly. If I add months this behavior is not like that anymore. (See problem 1 and problem 2 in the attached jsfiddle)

Second, if I have Months only (MMMM), there is an error when trying to do the following in xeditable.js:430. 

```
combodate.$widget.find('select').bind('change', function(e) {
          //.replace is so this works in Safari
          self.scope.$data = combodate.getValue() ?
              (new Date(combodate.getValue().replace(/-/g, "/"))).toISOString() : null;
        });
```

This problem can be seen in the jsfiddle problem 3. 

Finally, whenever a new date cannot be created in this line there is actually a problem. Let's say that we have dd/MM/YYYY like in problem 4. if the selected day is more then 12 it won't change, if it is less than 12 it will change the month instead.

In general there is a problem between date and format. 

a possible solution would be to use moment to parse the date with the specific format.

### PR DESCRIPTION
**Pull request by ckosloski**
- Fix editable-combodate for single date fields
- Fixes #705, #706

### CODE REVIEW

**Comment by ckosloski** [comment]
@josemonsalve2 please review

**Comment by josemonsalve2** [comment]
It looks good to me

**Comment by josemonsalve2** [comment]
Also, thanks for being so responsive

**Comment by eugef** [comment]
@ckosloski you are using `moment.js`, but it only a devDependency of the `angular-xeditble`.
I think me should mention in the documentation that for `editable-combodate` you need a `moment.js` installed as a global variable

**Comment by ckosloski** [comment]
@eugef the documentation already states you need moment.js for [combodate](http://vitalets.github.io/angular-xeditable/#combodate)

**Comment by josemonsalve2** [comment]
@ckosloski is right. I felt free to use moment.js due to the mention in the documentation.

**Pull request merged**
