### PR TITLE
Add support for checklist-comparator to editable-checklist

### LINKED ISSUE #558: Xeditable adds empty class/tag and uncheckes  selected checkbox in the checklist, when values are changed the child model.
xeditable **adds empty class/tag** and **uncheckes**  selected checkbox in the checklist, when values are changed the child model.

I have created fiddle and added steps to recreate the issue.
[http://jsfiddle.net/etsigankov/0twrL66q/](Fiddle)
Steps:
1. click add shape it will create the model
2. click "no appliances" and add 1 or two items(it adds items to the model and displays them)
3. once you change the measurement W or H( it records changes in the **model** correctly) BUT

Issue: if you go to "add appliance" ( it will uncheck everything that was checked before, thus creating multiple entries).

P.S. Everything works with Select/multi select

### PR DESCRIPTION
**Pull request by ckosloski**
- Add support for checklist-comparator to editable-checklist
- Fix some layout issues of the demo site on phones
- Closes #558, #183

### CODE REVIEW

**Comment by eugef** [comment]
@ckosloski how exactly #183 was fixed?

**Comment by ckosloski** [comment]
The documentation works fine on my phone.  The only issue I saw was some layout problems.  I fixed most of them.

**Comment by eugef** [comment]
ok, clear

**Comment by ckosloski** [comment]
@eugef can you do a new build?
Also, I just noticed that the change log doesn't reference the text-disable watch fix you merged - https://github.com/vitalets/angular-xeditable/commit/eb502edda10ee9fadb80583785f243790f2451e3

**Comment by eugef** [comment]
@ckosloski I'll do it today.

**Pull request merged**
