### PR TITLE
uib changes for datepicker, typeahead and timepicker

### PR DESCRIPTION
**Pull request by ckosloski**
Updated to use Angular 1.5.0, bootstrap 3.3.6, ui-bootstrap 1.2.4.  
Updated datepicker, typeahead, timepicker to use the new uib prefix.  
Fixed all all but 2 broken tests (which might be related to #414).

This replaces PR #406 

This should fix issues #440, #435, #428, #317

### CODE REVIEW

**Comment by eugef** [comment]
@ckosloski what exactly tests are broken?

**Comment by ckosloski** [comment]
@eugef All the tests were failing before.  The two tests failing now are the dev-text/blur = "submit" and blur = "cancel".

I didn't test if #414 would fix it or not.  I will take a look.

**Comment by ckosloski** [comment]
I have merged #414 into my pull request.  That change fixed the 2 broken tests.

**Comment by eugef** [comment]
Thanks @ckosloski, great job

**Comment by lalitkapoor** [comment]
@ckosloski thank you!

**Pull request merged**
