### PR TITLE
Fix cancel not cancelling for ngTagsInput

### LINKED ISSUE #617: x-editable ngTagsInput modifies the model on form blur/cancel.
Hi I was wondering if there was any way to stop the tagInputBox from changing the model of tag array if the user would press cancel. I want it to be such that any tag added in the current x-editable form would be removed but the ones that were there previously would stay. Even on the demo on the main site, the ng-tagsinput xeditable box saves the new tag to the tag model array.

Anyway to work around this?

### PR DESCRIPTION
**Pull request by ckosloski**
- Fix cancel not cancelling for ngTagsInput
- Closes #617

### CODE REVIEW

**Comment by eugef** [comment]
@ckosloski, would be nice to have a test that confirms the fix.

**Comment by ckosloski** [comment]
Test added

**Comment by eugef** [comment]
Does the test fail without your fix?

**Comment by ckosloski** [comment]
Tests re-arranged and it does fail if the change is removed.

**Comment by eugef** [comment]
Thanks

**Pull request merged**
