### PR TITLE
Onkeyup

### PR DESCRIPTION
**Pull request by qisaw**
Created a new property for an editable-element "onkeyup" which allows a user to do validation on every key press which is not enter or escape. This allows errors to be shown while the user is in the process of typing. However you may still save the form if there is an error shown due to the "onkeyup" property. This responsibility falls to the "onbeforesave" property. JSFidde http://jsfiddle.net/s5wothmw/3/

### CODE REVIEW

**Comment by bhamde** [comment]
+1 to merge

**Comment by ebuckley** [comment]
:+1 Looks good to me

**Comment by ckosloski** [comment]
I tried these changes locally and they didn't work for me.  The onkeyup function never gets called.
There was also an issue in the onkeyup/desc.md file that cause a formatting issue on the generated index file.
Also, the dist files need to be removed from the pull request.

**Comment by ckosloski** [comment]
@qisaw can you clean up your request?

**Comment by ckosloski** [comment]
@eugef Since the code doesn't work in the request, I propose it should be closed.

**Pull request closed without merging**
