### PR TITLE
Added ability to specify controlsTpl in a custom directive

### PR DESCRIPTION
**Pull request by ttonyh**
I added the ability to specify a "controlsTpl" property, overriding any referenced theme, in a custom directive. I found this useful when creating a custom xeditable directive that uses a custom, composite directive, made up of Angular Material elements.

The controls wrapper "md-input-container" was being applied over an existing one. This override allows me to use a DIV or something else (other than what's specified in the theme) and avoid having nested "md-input-container".

### CODE REVIEW

**Comment by eugef** [comment]
Hi @ttonyh, thanks for you PR. 
To be able to merge it - could you also add documentation how to use it and unit test.

**Comment by ttonyh** [comment]
@ eugef I'd be happy to. What's the documentation procedure for this project?

**Comment by eugef** [comment]
@ttonyh , just add information about new attribute to the `docs/jade/reference.jade` and also nice to add demo example as it is done for some other attributes.

**Comment by ttonyh** [comment]
@eugef Docs have been updated per your request, please review when you get the chance. Thanks :-)

**Comment by ckosloski** [comment]
You don't need the index.html, that gets generated on build.
For the demo example, create a new folder in docs/demos called `custom-template` or what ever seems appropriate.   Create a controller.js, desc.md, test.js, view.html (or copy them) and put in your example and tests.
You will also need to update `structure.js` with your new example

**Comment by ttonyh** [comment]
@ckosloski Ok, will do. Thank you!

**Comment by ckosloski** [comment]
@ttonyh can you update your request?

**Comment by eugef** [comment]
@ttonyh please include only `src/` files in your PR

**Comment by ckosloski** [comment]
@ttonyh Can you remove all the generated files from your request?

**Comment by ckosloski** [comment]
@ttonyh any update on this?

**Pull request closed without merging**
