### PR TITLE
Added title and aria-label to form buttons

### LINKED ISSUE #341: Feature Request: Custom Form Templates
- I want to be able to add my own button to the Save/Cancel set, e.g. a clear button to clear the input without making the user delete the value manually. Right now any additional buttons have to exist outside of the x-editable field area.
- I want to be able to add attributes to Save/Cancel, e.g. `title` and `aria-label` for accessibility. Furthermore I feel they should come with at least `aria-label` set by default; right now they are icons with no textual alternatives for assistive technology.
- I want to be able to add to the inputs, e.g. Bootstrap input group addons or labels.
- [This apparent solution](https://github.com/vitalets/angular-xeditable/issues/52#issuecomment-36794042) does not hook into the x-editable library at all, which means I can not use it the same way as any other input.

### PR DESCRIPTION
**Pull request by ckosloski**
- Add title to form buttons
- Add aria-label to form buttons
- Add configuration to display reset button
- Fix bstime css issue
- Add support for simple bootstrap input groups
- Closes #341

### CODE REVIEW

**Comment by eugef** [comment]
Thanks @ckosloski

**Comment by eugef** [comment]
@ckosloski new release is out

**Comment by letmejustfixthat** [comment]
How does this close #341? I can't find anything how to add custom buttons to the panel. Or did you just implement the actual use case described in #341?

**Comment by ckosloski** [comment]
There was nothing in that ticket about custom buttons solutions, I implemented the items listed in the issue.

- Point 1 - configuration to add a clear button was added.
- Point 2 - Title and aria-labels were added to the buttons
- Point 3 - Support was added for simple bootstrap input groups
- Point 4 - Skipped, not entirely sure what solution he was looking for there and no other comments in over a year.

**Comment by letmejustfixthat** [comment]
> I want to be able to add my own button to the Save/Cancel set, e.g. a clear button
I'm trying to add a button to completely remove the editable item from the model and hoped I just missed how to do that. But I guess that's not possible (without changes in the xeditable lib)?

**Pull request merged**
