### PR TITLE
Allow name attribute on checklist

### LINKED ISSUE #769: Does editable-checklist support e-name?
When one of checkbox is checked, I want some other elements to show or hide.
So I plan to use `editableForm['some-name']['$viewValue']`, but this is `undefined`.
I checked the html, but it seems that `name` is not added onto `input`.

### PR DESCRIPTION
**Pull request by ckosloski**
Allow name attribute on checklist

Fixes #769

### CODE REVIEW

**Comment by ckosloski** [comment]
>     1. I'm not sure if you want the name to be 'check_list[]' or just 'check_list' for 'data-e-name'. I checked the structure of editableForm, here is one of its attribute: $data: {name: "awesome", status: 2, group: 4}, I think 'check_list[]' is not a property name for the $data property.
> 
>     2. It is expected that editableForm['check_list[]']['$viewValue'] to be an array, is there such test?

1.  That is just a name I used for the test to make sure it was added.  It was from your example.
2.  I did not add a test to verify that the name exists on the element.  I did however test in the browser console that `document.getElementByName` returned all 3 of the checkboxes.

**Comment by sinall** [comment]
> > ```
> > 1. I'm not sure if you want the name to be 'check_list[]' or just 'check_list' for 'data-e-name'. I checked the structure of editableForm, here is one of its attribute: $data: {name: "awesome", status: 2, group: 4}, I think 'check_list[]' is not a property name for the $data property.
> > 
> > 2. It is expected that editableForm['check_list[]']['$viewValue'] to be an array, is there such test?
> > ```
> 
> 1. That is just a name I used for the test to make sure it was added.  It was from your example.
> 2. I did not add a test to verify that the name exists on the element.  I did however test in the browser console that `document.getElementByName` returned all 3 of the checkboxes.

If I specify 'check_list[]' as name, can I get editableForm['check_list[]']['$viewValue'] as values of selected checkboxes?

**Comment by ckosloski** [comment]
I did not try that.  I only added support of the name, just like other controls support the name.

**Comment by sinall** [comment]
> I did not try that. I only added support of the name, just like other controls support the name.

OK, the name part should be OK by your commit.

**Comment by ckosloski** [comment]
@eugef looks like you are good to merge.

**Pull request merged**
