### PR TITLE
Added support for Meteor.js packaging

### PR DESCRIPTION
**Pull request by dotansimha**
Hi @vitalets ,

I'm a package maintainer for Meteor.js, a popular full-stack JavaScript framework.
I'm also a developer on angular-meteor, a library that let's you work with AngularJS on top of Meteor.

A lot of our users use angular-xeditable and it right now there is a separate package and Github repo that simply manually copies your distribution and publish it to Meteor.
This PR will allow you to directly publish updated versions of angular-editable as they become available. All you have to do is create an account at https://meteor.com/ (click SIGN IN, then Create account). After you've done that, please let me know the name of the account, and I'll add you as a maintainer to the "vitalets" organization there.

I've already published the current version of the package on Atmosphere (Meteor's package directory). When you release new versions of angular-xeditable, you'll be able to publish them to Atmosphere by running `grunt meteor-publish` after updating the version number on the "package.js" file.

Thanks & best regards,
Dotan

### CODE REVIEW

**Comment by ckosloski** [comment]
@eugef is this still relevant?

**Comment by eugef** [comment]
@dotansimha can you update your PR?

**Comment by ckosloski** [comment]
@eugef what do you want to do with this pull request?

**Comment by eugef** [comment]
Don't think it is still relevant. npm & bower support should be enough

**Pull request closed without merging**
