### PR TITLE
Added support for ui-boostrap popover

### LINKED ISSUE #621: Not parsing popover options?
Maybe I'm just missing something, but I have a popover editable (which is lovely to have, thank you), with HTML like so:

```
<div class="popover-wrapper">
<a href="#" editable-text="name" onbeforesave="update()">{{name || 'Untitled'}}</a>
</div>
```

Presumably, on the wrapper, I'd like to add the following options, which seem to be ignored by 
`popover-append-to-body`
`placement="bottom"`

..which I also tried as
`e-popover-append-to-body`
`e-placement="bottom"`

I also tried them on the `<a>` tag, but alas, no dice. Many thanks to anyone that can point me in the right direction here.

### PR DESCRIPTION
**Pull request by ckosloski**
- Added support for ui-boostrap popover
- Fixes #621

### CODE REVIEW

**Comment by eugef** [comment]
@ckosloski thanks for the PR!

**Comment by lesliemklo** [comment]
When is the scheduled release for this feature? 👍

**Comment by ckosloski** [comment]
That's a question for @eugef

**Comment by eugef** [comment]
I'll do release this week

**Comment by lesliemklo** [comment]
awesome! thank you :)

**Comment by eugef** [comment]
Sorry for delay, release is out now

**Pull request merged**
