### PR TITLE
Made possible disabled of x-editable using global option of directive at...

### PR DESCRIPTION
**Pull request by hammat**
Hi,

I've been looking for a way to disable x-editable on specific conditions.
Somes issues that might be related #115 #109 #73

A working fiddle: http://jsfiddle.net/ce7gpvdd/5/

Feel free to give your feedbacks so we could improve it.

### CODE REVIEW

**Comment by abuechler** [comment]
Thanks @hammat!! Looking forward to get this merged.

**Comment by Nate-Wilkins** [comment]
@hammat <3

**Comment by sesh-kebab** [comment]
Thank you :+1:

**Comment by eparchas** [comment]
Thanks!

**Comment by RavenHursT** [comment]
Why hasn't this been merged yet?

**Comment by hammat** [comment]
No idea. It does the job and could be improved if needed.
I'm currently using the fork until it gets merged.

**Comment by RavenHursT** [comment]
+1 to @vitalets for a merge?

**Comment by gorebill** [comment]
cheers, but add follows code to line 861 in xeditable.js built file of ur fork would be better to disable it dynamically

if(scope.$eval(e.editable.attrs.editDisabled)) return;

**Comment by RavenHursT** [comment]
So is there any roadmap to getting this into a release?

**Comment by m2omou** [comment]
Thanks, that feature should be merged.

**Comment by jivasquez** [comment]
I made a small change on this so it checks the actual state of the edit-disabled attribute instead of the initial value of it on this pull request
https://github.com/vitalets/angular-xeditable/pull/282

**Pull request merged**
