### PR TITLE
Add ng-bind for input group

### LINKED ISSUE #713: e-inputgroup two way binding
It seems that the inputgroups are static and will not update when binding to a value:
`                                            <a editable-number="someScopeValue"
                                                    e-inputgroupleft="{{ someFunctionToCalcNewValue($data) }}">
                                                    {{ someScopeValue }}
                                                </a>`

### PR DESCRIPTION
**Pull request by ckosloski**
- Add ng-bind for input group
- Fixes #713

### CODE REVIEW

**Comment by ckosloski** [comment]
@dementic please review

**Comment by dementic** [comment]
Am away until the end of the month, will do as soon as I'm back.

**Comment by ckosloski** [comment]
@dementic Did you get a chance to review this yet?

**Comment by ckosloski** [comment]
@eugef You can go ahead and merge this and maybe do a new release?

**Pull request merged**
