### PR TITLE
Added attribute 'editable' to allow or disallow the edition of single inputs

### PR DESCRIPTION
**Pull request by sebastien-roch**
This works, see issue #109.
There is probably a better way to do this but I have not so much experience with angular. Let me know, I'm willing to improve this, it's just a start. Once approved I'll update the doc.

### CODE REVIEW

**Comment by mitcht** [comment]
I noticed, i've written almost the exact same thing in my pull request.  Fix for Issue #6

**Comment by sinsunsan** [comment]
hello, is this editable variable has been merged somehow ? 
I need to set editability depending of user rights.
So a simple attributes pointing a scope function or value could be useful in order not to duplicate the html code.

**Comment by mitcht** [comment]
Please update this pull req and fix conflicts.

**Comment by ckosloski** [comment]
I think this can be closed due to #235

**Pull request closed without merging**
