### PR TITLE
Added support for ngTagsInput

### LINKED ISSUE #365: ngTagsInput support question
Hi!
I try to implement support for ngTagsInput.I follow the code style of the most directives and the code is this.
angular.module('xeditable').directive('editableTag', ['editableDirectiveFactory',
  function(editableDirectiveFactory) {
    var dir= editableDirectiveFactory({
      directiveName: 'editableTag',
      inputTpl: '<tags-input display-property="tag" ></tags-input>',
      render: function() {
       this.parent.render.call(this); 
      }
    }); 
    return dir;
}
]);

Everything works as expected for the first time.
The second time this error occurs:

[$compile:ctreq] Controller 'tagsInput', required by directive 'tiTagItem', can't be found!

Can you please guide me on how i can solve this?

Thanks in advance...

### PR DESCRIPTION
**Pull request by ckosloski**
Added support for ngTagsInput.

Closes #365

### CODE REVIEW

**Comment by eugef** [comment]
@ckosloski, thanks for your commitment.

**Comment by eugef** [comment]
Tests are failing with the following error:
```
[$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module ngTagsInput due to:
Error: [$injector:nomod] Module 'ngTagsInput' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.0/$injector/nomod?p0=ngTagsInput
    at http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:68:12
    at http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:2015:17
    at ensure (http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:1939:38)
    at module (http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:2013:14)
    at http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:4503:22
    at forEach (http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:321:20)
    at loadModules (http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:4487:5)
    at http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:4504:40
    at forEach (http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:321:20)
    at loadModules (http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:4487:5)
http://errors.angularjs.org/1.5.0/$injector/modulerr?p0=ngTagsInput&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'ngTagsInput'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.0%2F%24injector%2Fnomod%3Fp0%3DngTagsInput%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A2015%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A1939%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A2013%3A14)%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A4503%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A4487%3A5)%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A4504%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A4487%3A5)
    at http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:68:12
    at http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:4526:15
    at forEach (http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:321:20)
    at loadModules (http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:4487:5)
    at http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:4504:40
    at forEach (http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:321:20)
    at loadModules (http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:4487:5)
    at createInjector (http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:4409:19)
    at doBootstrap (http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:1691:20)
    at Object.angular.resumeBootstrap (http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:1720:12)
http://errors.angularjs.org/1.5.0/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20ngTagsInput%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'ngTagsInput'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.0%2F%24injector%2Fnomod%3Fp0%3DngTagsInput%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A2015%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A1939%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A2013%3A14)%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A4503%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A4487%3A5)%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A4504%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A4487%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.0%2F%24injector%2Fmodulerr%3Fp0%3DngTagsInput%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'ngTagsInput'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.0%252F%2524injector%252Fnomod%253Fp0%253DngTagsInput%250A%2520%2520%2520%2520at%2520http%253A%252F%252F127.0.0.1%253A8000%252Flibs%252Fangular%252F1.5.0%252Fangular.js%253A68%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252F127.0.0.1%253A8000%252Flibs%252Fangular%252F1.5.0%252Fangular.js%253A2015%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252F127.0.0.1%253A8000%252Flibs%252Fangular%252F1.5.0%252Fangular.js%253A1939%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252F127.0.0.1%253A8000%252Flibs%252Fangular%252F1.5.0%252Fangular.js%253A2013%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F127.0.0.1%253A8000%252Flibs%252Fangular%252F1.5.0%252Fangular.js%253A4503%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252F127.0.0.1%253A8000%252Flibs%252Fangular%252F1.5.0%252Fangular.js%253A321%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252F127.0.0.1%253A8000%252Flibs%252Fangular%252F1.5.0%252Fangular.js%253A4487%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F127.0.0.1%253A8000%252Flibs%252Fangular%252F1.5.0%252Fangular.js%253A4504%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252F127.0.0.1%253A8000%252Flibs%252Fangular%252F1.5.0%252Fangular.js%253A321%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252F127.0.0.1%253A8000%252Flibs%252Fangular%252F1.5.0%252Fangular.js%253A4487%253A5)%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A4526%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A4487%3A5)%0A%20%20%20%20at%20http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A4504%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A321%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A4487%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A4409%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A1691%3A20)%0A%20%20%20%20at%20Object.angular.resumeBootstrap%20(http%3A%2F%2F127.0.0.1%3A8000%2Flibs%2Fangular%2F1.5.0%2Fangular.js%3A1720%3A12)
Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module ngTagsInput due to:
Error: [$injector:nomod] Module 'ngTagsInput' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.0/$injector/nomod?p0=ngTagsInput
    at http://127.0.0.1:8000/libs/angular/1.5.0/angular.js:68:12
```

@ckosloski, Could you please fix it.

**Comment by ckosloski** [comment]
Is this the doc tests or the dev tests?

**Comment by eugef** [comment]
dev

**Comment by ckosloski** [comment]
@eugef I did the following and I am not seeing any errors relating to ngTagsInput

- Rebased to master
- grunt jade
- grunt build
- http-server

Then browsed to http://127.0.0.1:8080/test/e2e/dev-test.html in Firefox/Chrome and Safari.

Am I testing differently from how you got the error?

**Comment by eugef** [comment]
I forgot to run grunt build :)

**Comment by ckosloski** [comment]
@eugef can you push out a new release?
Thanks

**Comment by eugef** [comment]
@ckosloski release is pushed

**Pull request merged**
